sudo: false

language: python

python:
  - 2.7
  - 3.4
  - 3.5

env:
  global:
    PYTHONPATH: src

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -q coverage
  - pip install -q coveralls
  - pip install -q lxml
  - pip install -q mock
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == 3 ]; then
    pip install suds-py3-fixes;
    else
    pip install suds;
    fi

before_script: cd tests

script: make coverage

after_script: coveralls --rc=coveragerc
