language: python

python:
  - 3.5
  - 3.6

install:
  - pip install -q coverage
  - pip install -q coveralls
  - pip install -q mock
  - pip install .

before_script: cd tests

script: make coverage

after_script: coveralls --rc=coveragerc
